#ifndef QGIT_VERSION_H
#define QGIT_VERSION_H

#define LIBQGIT2_VERSION "1.0.1"
#define LIBQGIT2_VER_MAJOR 1
#define LIBQGIT2_VER_MINOR 0
#define LIBQGIT2_VER_REVISION 1
#define LIBQGIT2_VER_PATCH 0

#define LIBQGIT2_SOVERSION "1.0"

#endif // QGIT_VERSION_H
